/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * react-pwa-ts.Server
 * OpenAPI spec version: 1.0
 */
import type { DayOfWeek } from './dayOfWeek';

export interface DateOnly {
  day?: number;
  readonly dayNumber?: number;
  dayOfWeek?: DayOfWeek;
  readonly dayOfYear?: number;
  month?: number;
  year?: number;
}
