/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * react-pwa-ts.Server
 * OpenAPI spec version: 1.0
 */

export interface NotificationSubscriptionKey {
  /** @nullable */
  auth?: string | null;
  /** @nullable */
  p256DH?: string | null;
}
