/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * react-pwa-ts.Server
 * OpenAPI spec version: 1.0
 */
import type { NotificationSubscriptionKey } from './notificationSubscriptionKey';

export interface NotificationSubscription {
  /** @nullable */
  endpoint?: string | null;
  keys?: NotificationSubscriptionKey;
}
