/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * react-pwa-ts.Server
 * OpenAPI spec version: 1.0
 */
import type { PostApiContentUploadBodyHeaders } from './postApiContentUploadBodyHeaders';

export type PostApiContentUploadBody = {
  ContentDisposition?: string;
  ContentType?: string;
  FileName?: string;
  Headers?: PostApiContentUploadBodyHeaders;
  Length?: number;
  Name?: string;
};
