/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * react-pwa-ts.Server
 * OpenAPI spec version: 1.0
 */

export interface PushNotificationMessage {
  /** @nullable */
  content?: string | null;
  /** @nullable */
  openUrl?: string | null;
  /** @nullable */
  title?: string | null;
}
