/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * react-pwa-ts.Server
 * OpenAPI spec version: 1.0
 */

export interface SaveTestValueModel {
  /** @nullable */
  value?: string | null;
}
