/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * react-pwa-ts.Server
 * OpenAPI spec version: 1.0
 */
import type { DateOnly } from './dateOnly';

export interface WeatherForecast {
  date?: DateOnly;
  /** @nullable */
  summary?: string | null;
  temperatureC?: number;
  readonly temperatureF?: number;
}
